Locales['en'] = {

	['robbery_cancelled'] = 'pljačka je otkazana!',
	['shop_robbery'] = 'Pljačka u nakitu',
	['press_to_rob'] = 'Pucaj da započneš pljačku',
	['seconds_remaining'] = '~w~ preostale sekunde',
	['robbery_cancelled_at'] = '~r~ pljačka je otkazana u: ~b~',
	['robbery_has_cancelled'] = '~r~ pljačka je otkazana: ~b~',
	['already_robbed'] = 'nakit je već opljačkan. Čekati: ',
	['seconds'] = 'sekunde.',
	['rob_in_prog'] = '~r~ pljačka u toku: ~b~',
	['started_to_rob'] = 'Ti si započeo pljačku ',
	['do_not_move'] = ', uzmi dragulje s prozora!',
	['alarm_triggered'] = 'alarm je aktiviran',
	['hold_pos'] = 'kad sakupiš sve dragulje, bježi!',
	['robbery_complete'] = '~r~ Pljačka je uspjela!~s~ ~h~ Bježite! ',
	['robbery_complete_at'] = '~r~ Pljačka je uspješna u: ~b~',
	['min_two_police'] = 'mora postojati barem ~b~',
	['min_two_police2'] = ' ~w~policajci u gradu za pljačku.',
	['robbery_already'] = '~r~Pljačka je već u toku.',
	['robbery_has_ended'] = 'Pljačka je završila',
	['end'] = 'Nakit je opljačkan!',
	['notenoughgold'] = '~r~Nemate dovoljno dragulja!',
	['copsforsell'] = 'mora postojati barem ~b~',
	['copsforsell2'] = ' ~w~policajci u gradu za prodaju.',
	['goldsell'] = '~y~Nakit~s~ prodaja u tijeku',
	['field'] = 'Pritisnite ~y~E~s~ da ~o~prikupiti~s~ draguljima',
	['collectinprogress'] = 'U toku je prikupljanje nakita ...',
	['lester'] = '~g~Opljačkali ste nakit! Sad ponesite dragulje ~r~Lestera!',
	['jewelsblipmap'] = 'Dragulji',
	['press_to_collect'] = 'skupljati dragulje',
	['smash_case'] = 'razbijeni prozori',
	['press_to_sell'] = 'Kliknite ~INPUT_PICKUP~ za da prodajes dragulju',
	['need_bag'] = 'Treba ti torba! Otiđite do najbliže odjeće, i uzmite torbu.'

}
